# Generated by Django 3.2 on 2021-06-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docuser',
            name='document_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invitemessage',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
