# Generated by Django 3.2 on 2021-06-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_docs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docs',
            new_name='Doc',
        ),
    ]
