# Generated by Django 3.2 on 2021-06-11 17:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_rename_docs_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
