# Generated by Django 3.2 on 2021-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_remove_group_leader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='leader_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
