# Generated by Django 3.2 on 2021-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_group_leader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='others_create_right',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='others_recycle_right',
            field=models.BooleanField(default=False),
        ),
    ]
