# Generated by Django 3.2 on 2021-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_auto_20210612_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('is_accept', models.BooleanField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='doc_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='is_group_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc',
            name='modify_right',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='others_modify_right',
            field=models.BooleanField(default=True),
        ),
    ]
